Update generate-content.yaml

diff --git a/.github/workflows/generate-content.yaml b/.github/workflows/generate-content.yaml
--- a/.github/workflows/generate-content.yaml
+++ b/.github/workflows/generate-content.yaml
@@ -42,9 +42,10 @@ jobs:
       - name: 🚀 Generate Course Content
         working-directory: .github/course-generator
         run: |
+          set -x
           echo "🎯 Starting content generation process..."
           ls -lrth
-          python3 todays_course_finder.py || echo "Failed to run the Python script" && exit 1
+          python3 todays_course_finder.py || echo "Failed to run the Python script"
         env:
           GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
 
