Update generate-content.yaml

diff --git a/.github/workflows/generate-content.yaml b/.github/workflows/generate-content.yaml
--- a/.github/workflows/generate-content.yaml
+++ b/.github/workflows/generate-content.yaml
@@ -44,7 +44,7 @@ jobs:
         run: |
           echo "🎯 Starting content generation process..."
           ls -lrth
-          python3 todays_course_finder.py
+          python3 todays_course_finder.py || echo "Failed to run the Python script" && exit 1
         env:
           GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
 
